### ISSUE TITLE
Fix MacOS Builds (pip ImportError: 'SCHEME_KEYS')

### ISSUE THREAD

**Issue by maltfield** [BusKill/buskill-app#20]
**Describe the bug**
Builds in the dev branch are failing, see:

 * https://github.com/BusKill/buskill-app/runs/2814490516?

**To Reproduce**

push changes on dev branch to github

**Expected behavior**

Builds should finish and spit-out a working dmg

**Screenshots**

**Versions (please complete the following information):**
 - OS: MacOS
 - BusKill: dev

**Additional context**

```
2021-06-13T17:05:42.6157790Z + PYTHON_PATH=/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/bin/python3.8
...
2021-06-13T17:05:42.7168160Z + PIP_PATH=/usr/local/Cellar/python@3.8/3.8.10/bin/pip3
...
2021-06-13T17:05:42.9342940Z + /usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/bin/python3.8 --version
2021-06-13T17:05:42.9417760Z Python 3.8.10
2021-06-13T17:05:42.9421310Z + /usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m pip list
2021-06-13T17:05:45.2528580Z Package    Version
2021-06-13T17:05:45.2530460Z ---------- -------
2021-06-13T17:05:45.2530910Z pip        21.1.1
2021-06-13T17:05:45.2531270Z setuptools 56.0.0
2021-06-13T17:05:45.2531660Z wheel      0.36.2
2021-06-13T17:05:50.3587140Z + which pip3
2021-06-13T17:05:50.3608340Z /usr/local/bin/pip3
2021-06-13T17:05:50.3610090Z + pip3 list
2021-06-13T17:05:52.2740810Z Package    Version
2021-06-13T17:05:52.2742170Z ---------- -------
2021-06-13T17:05:52.2743100Z pip        21.1.1
2021-06-13T17:05:52.2743880Z setuptools 56.0.0
2021-06-13T17:05:52.2744530Z wheel      0.36.2
...
2021-06-13T17:18:59.9047870Z + /usr/local/Cellar/python@3.8/3.8.10/bin/pip3 download python-gnupg
2021-06-13T17:19:00.1174990Z Traceback (most recent call last):
2021-06-13T17:19:00.1176070Z   File "/usr/local/Cellar/python@3.8/3.8.10/bin/pip3", line 33, in <module>
2021-06-13T17:19:00.1177770Z     sys.exit(load_entry_point('pip==21.1.1', 'console_scripts', 'pip3')())
2021-06-13T17:19:00.1178780Z   File "/usr/local/Cellar/python@3.8/3.8.10/bin/pip3", line 25, in importlib_load_entry_point
2021-06-13T17:19:00.1179620Z     return next(matches).load()
2021-06-13T17:19:00.1182660Z   File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
2021-06-13T17:19:00.1184520Z     module = import_module(match.group('module'))
2021-06-13T17:19:00.1185880Z   File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
2021-06-13T17:19:00.1187280Z     return _bootstrap._gcd_import(name[level:], package, level)
2021-06-13T17:19:00.1188190Z   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2021-06-13T17:19:00.1189050Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2021-06-13T17:19:00.1189970Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2021-06-13T17:19:00.1191060Z   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2021-06-13T17:19:00.1192040Z   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
2021-06-13T17:19:00.1193010Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-06-13T17:19:00.1194540Z   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
2021-06-13T17:19:00.1195710Z     from pip._internal.cli.autocompletion import autocomplete
2021-06-13T17:19:00.1198000Z   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
2021-06-13T17:19:00.1199500Z     from pip._internal.cli.main_parser import create_main_parser
2021-06-13T17:19:00.1201010Z   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
2021-06-13T17:19:00.1202250Z     from pip._internal.cli import cmdoptions
2021-06-13T17:19:00.1203760Z   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
2021-06-13T17:19:00.1205590Z     from pip._internal.cli.progress_bars import BAR_TYPES
2021-06-13T17:19:00.1207300Z   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 12, in <module>
2021-06-13T17:19:00.1208470Z     from pip._internal.utils.logging import get_indentation
2021-06-13T17:19:00.1210660Z   File "/usr/local/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 18, in <module>
2021-06-13T17:19:00.1211830Z     from pip._internal.utils.misc import ensure_dir
2021-06-13T17:19:00.1214120Z   File "/usr/local/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 31, in <module>
2021-06-13T17:19:00.1215210Z     from pip._internal.locations import (
2021-06-13T17:19:00.1216650Z   File "/usr/local/lib/python3.8/site-packages/pip/_internal/locations/__init__.py", line 7, in <module>
2021-06-13T17:19:00.1218040Z     from pip._internal.models.scheme import SCHEME_KEYS, Scheme
2021-06-13T17:19:00.1219920Z ImportError: cannot import name 'SCHEME_KEYS' from 'pip._internal.models.scheme' (/usr/local/lib/python3.8/site-packages/pip/_internal/models/scheme.py)```

**Comment by maltfield** [comment]
Unfortunately, the build output from the most-recently-run build that was successful is no longer available

 * https://github.com/BusKill/buskill-app/runs/1745438923

But my suspicion is that the python version changed. So far quick searches on the internet don't return anyone else experiencing the same issue.

**Comment by maltfield** [comment]
So one solution might be to just stop fighting with the GitHub/MacStadium (moving goalposts) python binary and package it myself in this repo like the rest of the depends.

**Comment by maltfield** [comment]
This was fixed last month by changing the `find` command for the python & pip binaries to match on `-wholename *bin/python3**`with grep instead of `/usr/local/Cellar/python@3.7`

It was merged into master here:

 * https://github.com/BusKill/buskill-app/commit/5b344cc6c9d824b617e5091a9b5db076b2005a94#diff-c6b96038d5f4e654446a075c32185c963a2308b93a432df53a52621b26fca0a4
